export const theme = {
  colors: {
    surface: '#FAF8FF',
    surfaceContainerLowest: '#FFFFFF',
    surfaceContainerLow: '#F2F3FF',
    surfaceContainer: '#EAEDFF',
    surfaceContainerHigh: '#E2E7FF',
    surfaceContainerHighest: '#DAE2FD',
    onSurface: '#131B2E',
    onSurfaceVariant: '#434655',
    primary: '#004AC6',
    primaryContainer: '#2563EB',
    onPrimary: '#FFFFFF',
    primaryFixed: '#DBE1FF',
    primaryFixedDim: '#B4C5FF',
    secondary: '#006C4A',
    secondaryBright: '#059669',
    secondaryContainer: '#82F5C1',
    onSecondaryContainer: '#00714E',
    secondaryFixed: '#85F8C4',
    secondaryFixedDim: '#68DBA9',
    tertiary: '#AE0010',
    tertiaryBright: '#DC2626',
    tertiaryContainer: '#D52022',
    onTertiaryContainer: '#FFECE2',
    tertiaryFixed: '#FFDAD6',
    tertiaryFixedDim: '#FFB4AB',
    error: '#BA1A1A',
    errorContainer: '#FFDAD6',
    outline: '#737686',
    outlineVariant: '#C3C6D7',
    inverseSurface: '#283044',
    inverseOnSurface: '#EEF0FF',
    warning: '#D97706',
    warningContainer: '#FFFBEB',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 20,
    xl: 24,
    xxl: 32,
  },
  radius: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 24,
    full: 9999,
  },
  typography: {
    fontFamily: 'System',
    statHero: {
      fontSize: 38,
      fontWeight: '800' as const,
      letterSpacing: -1,
    },
    headlineLg: {
      fontSize: 26,
      fontWeight: '700' as const,
      letterSpacing: -0.5,
    },
    headlineMd: {
      fontSize: 22,
      fontWeight: '700' as const,
      letterSpacing: -0.3,
    },
    headlineSm: {
      fontSize: 18,
      fontWeight: '600' as const,
      letterSpacing: -0.2,
    },
    statMonoMd: {
      fontSize: 20,
      fontWeight: '600' as const,
    },
    statMonoLg: {
      fontSize: 30,
      fontWeight: '700' as const,
      letterSpacing: -0.5,
    },
    bodyLg: {
      fontSize: 16,
      fontWeight: '400' as const,
    },
    bodyMd: {
      fontSize: 14,
      fontWeight: '400' as const,
    },
    bodySm: {
      fontSize: 12,
      fontWeight: '400' as const,
    },
    labelMd: {
      fontSize: 13,
      fontWeight: '600' as const,
    },
    labelSm: {
      fontSize: 11,
      fontWeight: '700' as const,
    },
    caption: {
      fontSize: 10,
      fontWeight: '600' as const,
      letterSpacing: 0.5,
    },
  },
};
